from lib.logging.logger import Feature
from lib.units import Units

feature_thrust = Feature("thrust", "motor.thrust", Units.N)
feature_CC_pressure = Feature("chamber pressure", "motor.combustion_chamber.pressure", Units.Pa)
feature_tank_pressure = Feature("tank pressure", "motor.ox_tank.pressure", Units.Pa)
feature_CC_temperature = Feature("chamber temperature", "motor.combustion_chamber.temperature", Units.K)
feature_tank_temperature = Feature("tank temperature", "motor.ox_tank.temperature", Units.K)
feature_grain_effective_radius = Feature("effective radius", "motor.combustion_chamber.fuel_grain.geometry.effective_radius", Units.m)
feature_OF = Feature("O/F", "motor.OF", Units.amount)
feature_cstar = Feature("cstar", "motor.combustion_chamber.cstar", Units.mps)
feature_specific_impulse = Feature("Isp", "motor.specific_impulse", Units.s)
feature_fuel_flow = Feature("fuel flow", "motor.fuel_flow", Units.kps)
feature_ox_flow = Feature("ox flow", "motor.ox_flow", Units.kps)
feature_mass_flow_in = Feature("mass flow in", "motor.mass_flow", Units.kps)
feature_mass_flow_out = Feature("mass flow out", "motor.mass_flow_out", Units.kps)
feature_CC_ideal_gas_constant = Feature("chamber gamma", "motor.combustion_chamber.ideal_gas_constant", Units.amount)
feature_propellant_CG = Feature("propellant CG", "motor.propellant_CG", Units.m)
feature_propellant_mass = Feature("propellant mass", "motor.propellant_mass", Units.kg)
feature_regression_rate = Feature("regression rate", "motor.combustion_chamber.fuel_grain.regression_rate", Units.mps)
feature_flux = Feature("total flux", "motor.combustion_chamber.fuel_grain.flux", Units.flux)
feature_port_area = Feature("port area", "motor.combustion_chamber.fuel_grain.geometry.port_area", Units.m2)
feature_burn_area = Feature("burn area", "motor.combustion_chamber.fuel_grain.geometry.burn_area", Units.m2)
feature_length_regressed = Feature("length regressed", "motor.combustion_chamber.fuel_grain.geometry.length_regressed", Units.m)
feature_nozzle_exit_pressure = Feature("exit pressure", "motor.nozzle.exit_pressure", Units.Pa)
feature_ox_mass = Feature("ox mass", "motor.ox_tank.ox_mass", Units.kg)
feature_ox_center_of_mass = Feature("ox COM", "motor.ox_tank.oxidizer_center_of_mass", Units.m)
feature_fuel_mass = Feature("fuel mass", "motor.fuel_grain.fuel_mass", Units.kg)
feature_fuel_CG = Feature("fuel COM", "motor.fuel_grain.total_CG", Units.m)

base_features = set([feature_thrust, feature_CC_pressure, feature_tank_pressure, feature_CC_temperature, feature_tank_temperature, feature_grain_effective_radius, feature_OF, feature_cstar, feature_specific_impulse, feature_fuel_flow, feature_ox_flow, feature_mass_flow_in, feature_mass_flow_out, feature_CC_ideal_gas_constant, feature_propellant_CG, feature_propellant_mass, feature_regression_rate, feature_flux, feature_port_area, feature_burn_area, feature_length_regressed, feature_nozzle_exit_pressure, feature_ox_mass, feature_ox_center_of_mass, feature_fuel_mass, feature_fuel_CG])