# Analysis functions to operate on a folder generated by the monte carlo simulation of a motor


from matplotlib import pyplot as plt
from Helpers.data import plot_all_sims, read_sims


def plot_exit_pressures(sims):
    plot_all_sims(sims, y="nozzle.exit_pressure")

    plt.ylabel("Pressure (Pa)")
    plt.xlabel("Time (s)")
    plt.title("Exit Pressures")

def display_exit_pressures(sims):
    plot_exit_pressures(sims)
    
    plt.show()



if __name__ == "__main__":
    sims = read_sims("./Analysis/MontecarloMotorData/MotorMonteCarloAccurateLoadDistribution-Temporary")
    display_exit_pressures(sims)
    pass